# Aplicando fórmula de PSI a las tablas de Covid

In [112]:
import pandas as pd
import numpy as np
import os
from pandas import DataFrame, Series 
mainpath = "C:/Users/Camila Saenz/Downloads/TAREAS/Supervised learning 1/" 
file = "covid utf-1.csv"
Y = "covid utf-2.csv"
data1 = pd.read_csv(file)
data2 = pd.read_csv(Y)

In [113]:
df1 = pd.read_csv('covid utf-1.csv')
df2 = pd.read_csv('covid utf-2.csv')

In [114]:
df1

Saldo  Saldo Promedio  Deuda Sistea    Pasivo     Venta
0    56643.10092     28321.55046      31365.73   5876.82  108400.0
1   190313.99460     63437.99818      64864.99   4467.40  105300.0
2   547601.57360    182533.85790     200239.32   5000.92   86600.0
3   283914.20840     94638.06947     112945.17    325.50  103000.0
4   142296.43840     47432.14612     144877.21      0.00  172920.0
..           ...             ...           ...       ...       ...
95  244225.71270     82224.11698     154027.21   2558.31   69500.0
96  120614.28130     40204.76044     104592.02   2558.31   37650.0
97  244225.71270     82224.11698     154027.21   2558.31   69500.0
98  332309.95450    110769.98480     150257.39  96883.44  115000.0
99  721245.36690    240415.12230     274793.54   2558.31   64040.0

[100 rows x 5 columns]

In [115]:
df2

Saldo-E  Saldo Promedio-E  Deuda Sistea-E  Pasivo-E   Venta-E
0   218752.07940      72917.359810        83730.71  37461.71   35500.0
1    10418.72805       3472.909350         3052.97   3194.57   17320.0
2   244225.71270      82224.116980       154027.21   2558.31   69500.0
3   244225.71270      82224.116980       154027.21   2558.31   69500.0
4   162443.67220      54147.890750      1354123.46  23618.14   27900.0
..           ...               ...             ...       ...       ...
95  272435.74980      90811.916590       230599.62  20881.74  121950.0
96   50617.66762      25308.833810        25001.25      0.02   40000.0
97    9275.44963       3091.816543         6081.01      0.01   69500.0
98   90194.14818      30064.716060        20540.23   2558.31   53320.0
99   86086.20852      28695.402840       194773.18   2558.31   40100.0

[100 rows x 5 columns]

In [116]:
s1 = df1['Saldo'] 
c1 = df2['Saldo-E']

In [117]:
s1

0      56643.10092
1     190313.99460
2     547601.57360
3     283914.20840
4     142296.43840
          ...     
95    244225.71270
96    120614.28130
97    244225.71270
98    332309.95450
99    721245.36690
Name: Saldo, Length: 100, dtype: float64

In [118]:
c1

0     218752.07940
1      10418.72805
2     244225.71270
3     244225.71270
4     162443.67220
          ...     
95    272435.74980
96     50617.66762
97      9275.44963
98     90194.14818
99     86086.20852
Name: Saldo-E, Length: 100, dtype: float64

In [119]:
r1 = [s1-c1]

In [120]:
r1

[0    -162108.97848
 1     179895.26655
 2     303375.86090
 3      39688.49570
 4     -20147.23380
           ...     
 95    -28210.03710
 96     69996.61368
 97    234950.26307
 98    242115.80632
 99    635159.15838
 Length: 100, dtype: float64]

In [121]:
d1 = [s1/c1]

In [122]:
d1

[0      0.258937
 1     18.266529
 2      2.242195
 3      1.162507
 4      0.875974
         ...    
 95     0.896453
 96     2.382849
 97    26.330337
 98     3.684385
 99     8.378176
 Length: 100, dtype: float64]

In [123]:
l1=np.log(d1)

In [124]:
l1

array([[-1.35116884e+00,  2.90507035e+00,  8.07455117e-01,
         1.50579260e-01, -1.32418833e-01,  2.77748176e-01,
        -7.09868178e-01,  7.59587321e-01,  1.19827882e+00,
         4.59431856e+00, -2.04639308e+00,  2.07812095e+00,
        -1.10104487e+00, -2.12165649e+00,  7.59882854e-01,
        -1.49450337e+00,  5.30153211e-02,  8.60005066e-01,
         8.37444713e-01, -2.98900042e-01, -2.94058814e+00,
         1.81056767e-01,  3.61386934e-01,  1.48771033e+00,
        -4.39555774e-03, -7.98552811e-01, -1.02125491e+00,
        -1.55878847e+00,  4.62983042e-01, -2.58741910e-01,
         9.39070500e-01,  1.62704585e+00, -1.43364086e+00,
        -4.40027250e-01,  3.66435651e-01, -5.18064531e-02,
         1.59139074e+00,  4.03412365e-01,  1.92666988e+00,
         1.26913239e+00,  6.65656701e-01,  1.92995994e+00,
         1.59706797e+00, -2.76408884e+00, -1.40046971e+00,
        -4.27069453e+00,  4.70434569e+00,  2.45872863e-01,
         1.33335072e+00,  7.70352501e-01,  1.65833493e-0

In [125]:
s2 = df1['Saldo Promedio'] 
c2 = df2['Saldo Promedio-E']
r2 = [s2-c2]
d2 = [s2/c2]
l2=np.log(d2)
l2

array([[-9.45703727e-01,  2.90507035e+00,  7.97487026e-01,
         1.40611168e-01, -1.32418834e-01,  2.77748176e-01,
        -7.09868178e-01,  7.59587321e-01,  1.19827882e+00,
         4.59431856e+00, -2.04639308e+00,  2.07812095e+00,
        -6.95579763e-01, -2.12165649e+00,  7.49914763e-01,
        -1.49450337e+00,  5.30153210e-02,  8.60005066e-01,
         8.37444713e-01, -2.98900042e-01, -2.94058814e+00,
         1.81056767e-01,  3.61386934e-01,  1.48771033e+00,
        -4.39555797e-03, -7.98552811e-01, -1.02125491e+00,
        -1.55878847e+00,  4.62983042e-01, -6.64207018e-01,
         9.49038592e-01,  1.63701394e+00, -1.43364086e+00,
        -4.40027250e-01,  3.66438045e-01, -5.18064532e-02,
         1.59139074e+00,  4.03412365e-01,  1.92666988e+00,
         1.27910048e+00,  6.75624793e-01,  1.92995994e+00,
         1.59706797e+00, -2.76408884e+00, -1.40046971e+00,
        -4.27069453e+00,  4.70434569e+00,  2.45872863e-01,
         1.33335072e+00,  7.70352501e-01,  1.65833493e-0

In [126]:
s3 = df1['Deuda Sistea'] 
c3 = df2['Deuda Sistea-E']
r3 = [s3-c3]
d3 = [s3/c3]
l3=np.log(d3)
l3

array([[-0.98188992,  3.05619315,  0.26238398, -0.3102268 , -2.23502307,
         0.14969418,  0.25174977, -0.19899964,  1.21943248,  0.33438518,
        -1.77142434,  2.53513432,  1.49564428, -2.02936798,  1.08771601,
        -2.30478977, -1.14073666,  0.87295683,  2.73682129,  1.42165679,
        -2.79046795,  0.34424017,  0.35584384,  0.68033354, -1.20745756,
        -0.93281363, -1.12663668, -0.51796918, -1.13528411, -0.72145214,
         0.16066512,  2.31068397, -1.52909319, -0.46382804,  0.29701397,
        -0.40163841,  0.25131652, -0.51198321,  2.44842999, -0.44131366,
         1.31286965,  0.6648659 , -2.00885442, -2.59253999, -1.79598112,
        -4.35222181,  4.68049808,  0.27233706,  1.33522051,  0.27463224,
         0.94189344,  0.47569966, -0.47395432,  0.45035202,  5.08739704,
        -1.0191369 ,  3.29690304, -3.68011207,  1.76813179,  0.02607688,
         0.56371891,  2.05245818, -1.33240704,  2.3618814 ,  0.30088309,
        -4.26783504,  1.76068744,  1.92437182,  1.1

In [127]:
s4 = df1['Pasivo'] 
c4 = df2['Pasivo-E']
r4 = [s4-c4]
d4 = [s4/c4]
l4 = np.log(d4)
l4

C:\Users\CAMILA~1\AppData\Local\Temp/ipykernel_13064/3321169731.py:5: RuntimeWarning: divide by zero encountered in log
  l4 = np.log(d4)


array([[ -1.85230355,   0.33535409,   0.67027501,  -2.0617397 ,
                -inf, -12.66763809,  -1.86663412,   3.81632829,
                -inf,  -3.1539871 ,  -0.86020891,   3.55997922,
          3.15627951,  -2.96281067,   0.83467961,  -0.6984984 ,
                 inf,   0.67486561,   2.76055065,  -1.77361737,
         -5.34961066, -11.75912517,   1.21172007,   3.2202328 ,
         -2.81033365,  -6.52416975,  -4.77992097,  -0.67324206,
          3.70551583,  -7.63932157,   0.        ,  12.45227235,
          1.36822393,   0.        ,  -3.18426871,   2.21426197,
          8.1882005 ,   0.        ,   2.13248786,  -3.40747878,
                 inf,   0.26321061,   0.46184619,   2.35550321,
          3.63849023,   1.05811916,  -2.45843441,   6.50104799,
          1.91845195,   1.18335352,  -6.77209974,   0.15776377,
          8.29338927,   4.94641661,   1.32854738,  -3.09198368,
          0.44070051,          inf,   0.7124725 ,   1.43236612,
          0.        ,   1.3795724 , -12.

In [128]:
s5 = df1['Venta'] 
c5 = df2['Venta-E']
r5 = [s5-c5]
d5 = [s5/c5]
l5 = np.log(d5)
l5

array([[ 1.11629539e+00,  1.80495152e+00,  2.19973063e-01,
         3.93402236e-01,  1.82420237e+00,  6.43385016e-01,
        -1.10155513e+00,  3.37499458e-01,  2.04616906e+00,
        -1.48419858e+00, -2.33177080e-01,  6.00816642e-01,
         2.93834671e+00, -1.79856956e+00,  7.45357321e-01,
         6.57807814e-01,  1.32131130e+00,  2.70766643e+00,
         2.58405561e+00, -8.84332218e-01, -2.65754117e-01,
         6.85978691e-01,  1.61611016e+00,  5.71716195e-01,
         6.39913324e-01,  7.02908523e-01, -9.07693885e-01,
         7.91127589e-01,  3.38608639e-01,  2.03193640e+00,
         6.23943300e-01, -7.92699494e-01, -9.99643672e-01,
         8.67832463e-01,  5.46997977e-01,  3.30841518e-02,
         4.59953293e-01, -1.57648716e+00,  4.66666265e-01,
        -6.44500891e-01, -1.78257840e-02,  4.70128621e-01,
        -2.09721514e+00,  1.55814462e+00,  2.32638083e+00,
        -2.59201518e+00, -1.24999219e-05,  1.63226048e+00,
         7.09076464e-01, -2.74270742e-01, -1.18088285e+0